"""Python API for the zmux v1 single-connection stream multiplexer.

The PyPI distribution is named ``zmuxio`` and the import package is ``zmux``.

Public APIs live in explicit submodules such as ``zmux.protocol``,
``zmux.config``, ``zmux.native``, ``zmux.session``, ``zmux.streams``,
``zmux.transports``, and ``zmux.errors``.  The root package also provides a lazy facade for selected
stable symbols, so ``import zmux`` stays cheap while ``zmux.FrameType`` and
``from zmux import FrameType`` work as normal package-level API.
"""

from __future__ import annotations

from importlib import import_module as _import_module

__version__ = "0.1.0"

_EXPORT_MODULES = (
    "protocol",
    "config",
    "errors",
    "session",
    "native",
    "streams",
    "transports",
    "payload",
    "frame",
    "preface",
    "tlv",
    "varint",
    "settings",
    "conformance",
    "events",
)

_EXPORT_CACHE: dict[str, tuple[str, str]] = {}


def __getattr__(name: str):
    target = _find_export(name)
    if target is None:
        raise AttributeError("module %r has no attribute %r" % (__name__, name))
    module_name, attr_name = target
    value = getattr(_import_module("." + module_name, __name__), attr_name)
    globals()[name] = value
    return value


def __dir__():
    return sorted(set(globals()) | set(__all__))


def _find_export(name: str) -> tuple[str, str] | None:
    cached = _EXPORT_CACHE.get(name)
    if cached is not None:
        return cached
    for module_name in _EXPORT_MODULES:
        module = _import_module("." + module_name, __name__)
        if name in getattr(module, "__all__", ()):
            target = (module_name, name)
            _EXPORT_CACHE[name] = target
            return target
    return None


__all__ = (
    "__version__",
    'ACCEPT_TIMEOUT_MESSAGE',
    'ADAPTER_UNSUPPORTED_MESSAGE',
    'AbuseStats',
    'AcceptBacklogStats',
    'AcceptTimeout',
    'ActiveStreamStats',
    'AdapterUnsupported',
    'Address',
    'ApplicationError',
    'AsyncByteReceiveStream',
    'AsyncByteSendStream',
    'AsyncByteStream',
    'AsyncClosedSession',
    'AsyncInvalidSession',
    'AsyncRecvStream',
    'AsyncSendStream',
    'AsyncSession',
    'AsyncStream',
    'AsyncStreamHandle',
    'BasicDuplexTransport',
    'CAPABILITY_METADATA_CARRIAGE_MASK',
    'CAPABILITY_OPEN_METADATA',
    'CAPABILITY_PRIORITY_HINTS',
    'CAPABILITY_PRIORITY_UPDATE',
    'CAPABILITY_STREAM_GROUPS',
    'CLAIM_API_SEMANTICS_PROFILE_V1',
    'CLAIM_OPEN_METADATA',
    'CLAIM_PRIORITY_UPDATE',
    'CLAIM_STREAM_ADAPTER_PROFILE_V1',
    'CLAIM_WIRE_V1',
    'CORE_MODULE_TARGET_CLAIMS',
    'CORE_MODULE_TARGET_IMPLEMENTATION_PROFILES',
    'CORE_MODULE_TARGET_SUITES',
    'Capability',
    'Claim',
    'ClosedSession',
    'Config',
    'Conn',
    'ConformanceSuite',
    'DEFAULT_ABUSE_WINDOW',
    'DEFAULT_ACCEPT_BACKLOG_BYTES_FLOOR',
    'DEFAULT_ACCEPT_BACKLOG_LIMIT',
    'DEFAULT_ACCEPT_BACKLOG_PER_STREAM_BYTES_FLOOR',
    'DEFAULT_ACCEPT_BACKLOG_PER_STREAM_FRAMES',
    'DEFAULT_ACCEPT_BACKLOG_SESSION_FACTOR',
    'DEFAULT_CAPABILITIES',
    'DEFAULT_CLOSE_DRAIN_TIMEOUT',
    'DEFAULT_GO_AWAY_DRAIN_INTERVAL',
    'DEFAULT_GROUP_REBUCKET_CHURN_BUDGET',
    'DEFAULT_HIDDEN_ABORT_CHURN_BUDGET',
    'DEFAULT_HIDDEN_ABORT_CHURN_WINDOW',
    'DEFAULT_IGNORED_CONTROL_BUDGET',
    'DEFAULT_INBOUND_CONTROL_BYTES_BUDGET_FLOOR',
    'DEFAULT_INBOUND_CONTROL_FRAME_BUDGET',
    'DEFAULT_INBOUND_EXT_BYTES_BUDGET_FLOOR',
    'DEFAULT_INBOUND_EXT_FRAME_BUDGET',
    'DEFAULT_INBOUND_PING_BUDGET',
    'DEFAULT_KEEPALIVE_INTERVAL',
    'DEFAULT_KEEPALIVE_MAX_PING_INTERVAL',
    'DEFAULT_LATE_DATA_AGGREGATE_CAP_FLOOR',
    'DEFAULT_LATE_DATA_PER_STREAM_CAP_FLOOR',
    'DEFAULT_MAX_PROVISIONAL_STREAMS_BIDI',
    'DEFAULT_MAX_PROVISIONAL_STREAMS_UNI',
    'DEFAULT_NO_OP_BLOCKED_BUDGET',
    'DEFAULT_NO_OP_MAX_DATA_BUDGET',
    'DEFAULT_NO_OP_PRIORITY_UPDATE_BUDGET',
    'DEFAULT_NO_OP_ZERO_DATA_BUDGET',
    'DEFAULT_PENDING_CONTROL_BYTES_BUDGET_FLOOR',
    'DEFAULT_PENDING_PRIORITY_BYTES_BUDGET_FLOOR',
    'DEFAULT_PER_STREAM_QUEUED_DATA_HIGH_WATERMARK_FLOOR',
    'DEFAULT_PING_PADDING_MAX_BYTES',
    'DEFAULT_PING_PADDING_MIN_BYTES',
    'DEFAULT_PREFACE_PADDING_MAX_BYTES',
    'DEFAULT_PREFACE_PADDING_MIN_BYTES',
    'DEFAULT_READ_CHUNK',
    'DEFAULT_RETAINED_OPEN_INFO_BYTES_BUDGET',
    'DEFAULT_RETAINED_PEER_REASON_BYTES_BUDGET',
    'DEFAULT_SESSION_MEMORY_HARD_CAP_FLOOR',
    'DEFAULT_SESSION_QUEUED_DATA_HIGH_WATERMARK_FLOOR',
    'DEFAULT_STOP_SENDING_GRACEFUL_DRAIN_WINDOW',
    'DEFAULT_STOP_SENDING_GRACEFUL_DRAIN_WINDOW_MAX',
    'DEFAULT_TOMBSTONE_LIMIT',
    'DEFAULT_URGENT_QUEUE_MAX_BYTES_FLOOR',
    'DEFAULT_USED_MARKER_LIMIT',
    'DEFAULT_VISIBLE_TERMINAL_CHURN_BUDGET',
    'DEFAULT_VISIBLE_TERMINAL_CHURN_WINDOW',
    'DEFAULT_WRITE_BATCH_MAX_FRAMES',
    'DEFAULT_WRITE_CHUNK',
    'DEFAULT_WRITE_QUEUE_MAX_BYTES',
    'DIAG_DEBUG_TEXT',
    'DIAG_OFFENDING_FRAME_TYPE',
    'DIAG_OFFENDING_STREAM_ID',
    'DIAG_RETRY_AFTER_MILLIS',
    'DataPayload',
    'DataPayloadView',
    'Deadline',
    'DiagnosticStats',
    'DiagnosticType',
    'DuplexTransportControl',
    'EMPTY_METADATA_UPDATE_MESSAGE',
    'EXT_PRIORITY_UPDATE',
    'EmptyMetadataUpdate',
    'ErrorCode',
    'ErrorDirection',
    'ErrorOperation',
    'ErrorScope',
    'ErrorSource',
    'Event',
    'EventType',
    'ExtensionSubtype',
    'FRAME_FLAG_FIN',
    'FRAME_FLAG_MASK',
    'FRAME_FLAG_OPEN_METADATA',
    'FRAME_FLAG_RESERVED_TYPE_SPECIFIC',
    'FRAME_TYPE_MASK',
    'FileReadHalf',
    'FileWriteHalf',
    'FlowControlError',
    'FlushStats',
    'Frame',
    'FrameSizeError',
    'FrameType',
    'FrameView',
    'GRACEFUL_CLOSE_TIMEOUT_MESSAGE',
    'GoAwayPayload',
    'GracefulCloseTimeout',
    'HiddenStats',
    'ImplementationProfile',
    'InvalidSession',
    'JOINED_HALF_PAUSE_TIMEOUT_MESSAGE',
    'JoinedHalfPauseTimeout',
    'JoinedTransport',
    'KEEPALIVE_TIMEOUT_MESSAGE',
    'KNOWN_CLAIMS',
    'KNOWN_CONFORMANCE_SUITES',
    'KNOWN_IMPLEMENTATION_PROFILES',
    'KeepaliveTimeout',
    'Limits',
    'LivenessStats',
    'MAGIC',
    'MAX_PREFACE_SETTINGS_BYTES',
    'MAX_RETAINED_IO_BUFFER',
    'MAX_VARINT62',
    'MAX_VARINT_LEN',
    'METADATA_OPEN_INFO',
    'METADATA_STREAM_GROUP',
    'METADATA_STREAM_PRIORITY',
    'MemoryStats',
    'MetadataType',
    'MetadataUpdate',
    'NIL_CONN_MESSAGE',
    'Negotiated',
    'NativeStream',
    'NilConnection',
    'OPEN_EXPIRED_MESSAGE',
    'OPEN_INFO_UNAVAILABLE_MESSAGE',
    'OPEN_LIMITED_MESSAGE',
    'OPEN_METADATA_TOO_LARGE_MESSAGE',
    'OPEN_TIMEOUT_MESSAGE',
    'OpenExpired',
    'OpenInfoUnavailable',
    'OpenLimited',
    'OpenMetadataTooLarge',
    'OpenOptions',
    'OpenTimeout',
    'PING_TIMEOUT_MESSAGE',
    'PREFACE_VERSION',
    'PRIORITY_UPDATE_TOO_LARGE_MESSAGE',
    'PRIORITY_UPDATE_UNAVAILABLE_MESSAGE',
    'PROFILE_REFERENCE_V1',
    'PROFILE_V1',
    'PROTO_VERSION',
    'ParseConformanceError',
    'PausedReadHalf',
    'PausedWriteHalf',
    'PingTimeout',
    'Preface',
    'PressureStats',
    'PriorityUpdateTooLarge',
    'PriorityUpdateUnavailable',
    'ProgressStats',
    'ProtocolError',
    'ProvisionalStats',
    'QueueStats',
    'READ_SIDE_CLOSED_MESSAGE',
    'READ_TIMEOUT_MESSAGE',
    'REFERENCE_PROFILE_CLAIM_GATE',
    'ReadClosed',
    'ReadHalf',
    'ReadTimeout',
    'ReadableBuffer',
    'ReasonStats',
    'RecvStream',
    'RetainedBucketStats',
    'RetainedStateBreakdownStats',
    'RetentionStats',
    'Role',
    'SESSION_CLOSED_MESSAGE',
    'SESSION_WAIT_TIMEOUT_MESSAGE',
    'SETTING_INITIAL_MAX_DATA',
    'SETTING_INITIAL_MAX_STREAM_DATA_BIDI_LOCALLY_OPENED',
    'SETTING_INITIAL_MAX_STREAM_DATA_BIDI_PEER_OPENED',
    'SETTING_INITIAL_MAX_STREAM_DATA_UNI',
    'SETTING_MAX_CONTROL_PAYLOAD_BYTES',
    'SETTING_MAX_EXTENSION_PAYLOAD_BYTES',
    'SETTING_MAX_FRAME_PAYLOAD',
    'SETTING_MAX_INCOMING_STREAMS_BIDI',
    'SETTING_MAX_INCOMING_STREAMS_UNI',
    'SETTING_PING_PADDING_KEY',
    'SETTING_PREFACE_PADDING',
    'SETTING_SCHEDULER_HINTS',
    'STREAM_CLOSED_MESSAGE',
    'STREAM_NOT_READABLE_MESSAGE',
    'STREAM_NOT_WRITABLE_MESSAGE',
    'SUITE_API_SEMANTICS_PROFILE',
    'SUITE_CORE_FLOW_CONTROL',
    'SUITE_CORE_SESSION_LIFECYCLE',
    'SUITE_CORE_STREAM_LIFECYCLE',
    'SUITE_CORE_WIRE_INTEROPERABILITY',
    'SUITE_EXTENSION_TOLERANCE',
    'SUITE_INVALID_INPUT_HANDLING',
    'SUITE_OPEN_METADATA',
    'SUITE_PRIORITY_HINTS_AND_STREAM_GROUPS',
    'SUITE_PRIORITY_UPDATE',
    'SUITE_REFERENCE_PROFILE_CLAIM_GATE',
    'SUITE_REFERENCE_QUALITY_BEHAVIORS',
    'SUITE_STREAM_ADAPTER_PROFILE',
    'SUITE_V1_PROFILE_COMPATIBILITY',
    'SchedulerHint',
    'SendStream',
    'Session',
    'SessionClosed',
    'SessionState',
    'SessionStats',
    'SessionWaitTimeout',
    'SettingID',
    'Settings',
    'SocketTransport',
    'Stream',
    'StreamClosed',
    'StreamEventInfo',
    'StreamHandle',
    'StreamMetadata',
    'StreamMetadataView',
    'StreamNotReadable',
    'StreamNotWritable',
    'SyncByteReceiveStream',
    'SyncByteSendStream',
    'SyncByteStream',
    'TelemetryStats',
    'TerminationKind',
    'Tlv',
    'TlvView',
    'TransportError',
    'WRITE_SIDE_CLOSED_MESSAGE',
    'WRITE_TIMEOUT_MESSAGE',
    'WriteClosed',
    'WriteHalf',
    'WriteTimeout',
    'WritableBuffer',
    'WriterQueueStats',
    'ZmuxError',
    'ZmuxInterruptedError',
    'ZmuxSocketAddress',
    'ZmuxTimeoutError',
    'adapter_unsupported',
    'append_packed_varint',
    'append_setting_varint_tlv',
    'append_settings_tlv',
    'append_tlv',
    'append_varint',
    'as_async_session',
    'as_session',
    'as_structured_error',
    'async_closed_session',
    'build_error_payload',
    'build_go_away_payload',
    'build_open_metadata_prefix',
    'build_priority_update_payload',
    'capabilities_can_carry_group_in_update',
    'capabilities_can_carry_group_on_open',
    'capabilities_can_carry_open_info',
    'capabilities_can_carry_priority_in_update',
    'capabilities_can_carry_priority_on_open',
    'capabilities_have_peer_visible_group_semantics',
    'capabilities_have_peer_visible_priority_semantics',
    'capabilities_support_open_metadata',
    'capabilities_support_priority_update',
    'client',
    'clone_config',
    'closed_session',
    'code',
    'configure_default_config',
    'core_module_target_claims',
    'core_module_target_implementation_profiles',
    'core_module_target_suites',
    'deadline_after',
    'decode_varint_value',
    'default_accept_backlog_bytes_limit',
    'default_config',
    'default_late_data_aggregate_cap',
    'default_preface',
    'default_settings',
    'direction',
    'empty_metadata_update',
    'encode_tlvs',
    'encode_varint',
    'encode_varint_into',
    'encoded_len_from_first',
    'error_code_name',
    'find_error',
    'graceful_close_timeout',
    'has_all_capabilities',
    'has_any_capability',
    'has_capability',
    'has_code',
    'inbound_payload_limit',
    'interrupted',
    'is_error_code',
    'iter_tlvs_view',
    'join',
    'keepalive_timeout',
    'known_claims',
    'known_conformance_suites',
    'known_implementation_profiles',
    'known_setting_seen_bit',
    'marshal_frame',
    'marshal_preface',
    'marshal_preface_with_settings_padding',
    'marshal_settings_tlv',
    'maybe_timeout',
    'negotiate_prefaces',
    'normalize_limits',
    'open',
    'open_expired',
    'open_info_unavailable',
    'open_limited',
    'open_metadata_too_large',
    'operation',
    'pack_varint',
    'parse_data_payload',
    'parse_data_payload_metadata_offset',
    'parse_data_payload_view',
    'parse_diag_reason',
    'parse_error_payload',
    'parse_frame',
    'parse_frame_view',
    'parse_go_away_payload',
    'parse_preface',
    'parse_preface_prefix',
    'parse_priority_update_payload',
    'parse_settings_tlv',
    'parse_stream_metadata_bytes_view',
    'parse_stream_metadata_tlvs',
    'parse_stream_metadata_tlvs_view',
    'parse_tlvs',
    'parse_tlvs_view',
    'parse_varint',
    'priority_update_too_large',
    'priority_update_unavailable',
    'random_ping_padding_len',
    'random_preface_padding',
    'random_varint62',
    'read_closed',
    'read_frame',
    'read_preface',
    'read_varint',
    'reason',
    'reference_profile_claim_gate',
    'reset_default_config',
    'resolve_roles',
    'scope',
    'session_closed',
    'setting_varint_tlv_len',
    'settings_entries',
    'settings_tlv_len',
    'source',
    'source_exception',
    'server',
    'stream_closed',
    'stream_not_readable',
    'stream_not_writable',
    'termination_kind',
    'timeout',
    'tlv_encoded_len',
    'tlv_parse_capacity_hint',
    'typed_code',
    'validate_decoded_varint',
    'validate_frame',
    'validate_tlv_header',
    'validate_tlvs',
    'varint_len',
    'visit_tlvs',
    'write_closed',
    'write_frame',
    'write_preface',
)
