"""Constants for the aioquic adapter."""

from __future__ import annotations

from zmux.protocol import (
    CAPABILITY_OPEN_METADATA,
    CAPABILITY_PRIORITY_HINTS,
    CAPABILITY_STREAM_GROUPS,
)

STREAM_PRELUDE_MAX_PAYLOAD = 16 * 1024
DEFAULT_ACCEPTED_PRELUDE_READ_TIMEOUT = 5.0
DEFAULT_ACCEPTED_PRELUDE_MAX_CONCURRENT = 8
MAX_ACCEPTED_PRELUDE_MAX_CONCURRENT = 1024
ACCEPTED_PRELUDE_RESULT_QUEUE_CAP = 32
WRITEV_COALESCE_MAX_BYTES = 64 * 1024
OPEN_METADATA_CAPABILITIES = (
        CAPABILITY_OPEN_METADATA | CAPABILITY_PRIORITY_HINTS | CAPABILITY_STREAM_GROUPS
)
MAX_REASON_STATS_CODES = 1024
_EMPTY_STREAM_PRELUDE = b"\x00"

__all__ = (
    "ACCEPTED_PRELUDE_RESULT_QUEUE_CAP",
    "DEFAULT_ACCEPTED_PRELUDE_MAX_CONCURRENT",
    "DEFAULT_ACCEPTED_PRELUDE_READ_TIMEOUT",
    "MAX_ACCEPTED_PRELUDE_MAX_CONCURRENT",
    "OPEN_METADATA_CAPABILITIES",
    "STREAM_PRELUDE_MAX_PAYLOAD",
    "WRITEV_COALESCE_MAX_BYTES",
)
